### ISSUE TITLE
время после паузы

### ISSUE THREAD

**Issue by craveman** [craveman/Remote-Control#3]
ТОЛЬКО ДЛЯ САБЛИ
В сабле пауза 1 минута между периодами обычно делается при достижения одним из бойцов счета 8 (в бое на 15 уколов). Это сделано по тому что сабельный настолько скоротечен чтоо розыгрыш одной фразы редко занимает больше 3-4 секунд. Поэтому, после минутной паузы, время боя не сбрасывается на 3.00 а продолжается дальше.

**Comment by craveman** [comment]
здесь все так же

**Comment by Shander0** [comment]
fixed, need to test

**Comment by craveman** [comment]
Работает!
