### ISSUE TITLE
Сброс синхронизации при выключении экрана

### ISSUE THREAD

**Issue by craveman** [craveman/Remote-Control#5]
На всех, кроме samsung s8 при выключении экрана через некоторое время синхронизация сбрасывается. Проблема в том, что RC после этого очень долго (минуту и более) "не видит" SM-02 и не предлагает ввести код.

**Comment by Shander0** [comment]
fixed (reconnect after screen re-on), need to test

**Comment by craveman** [comment]
нет работает
